const { withAppBuildGradle } = require('@expo/config-plugins')

// Release signing, injected into the generated Gradle build: `android/` is regenerated by every
// prebuild, and without this the Expo template's release build type signs with the *debug*
// keystore, which Play refuses at upload — a failure that surfaces at the last possible step.
//
// The credentials are read by Gradle at build time rather than by this plugin at prebuild time, so
// `keystore.properties` (gitignored, see the `.example` beside it) can arrive after the native
// project was generated and the same checkout can prebuild on a machine that holds no keystore.
const MARKER = 'Release signing'

const GRADLE_BLOCK = `
// ${MARKER}
// Lives in apps/mobile/, one level above the generated android/ that prebuild rewrites.
def releaseKeystoreProps = rootProject.file("../keystore.properties")

if (releaseKeystoreProps.exists()) {
    def props = new Properties()
    releaseKeystoreProps.withInputStream { props.load(it) }

    def resolveStoreFile = { String path ->
        def candidate = new File(path)
        candidate.isAbsolute() ? candidate : new File(releaseKeystoreProps.parentFile, path)
    }

    android {
        signingConfigs {
            release {
                storeFile resolveStoreFile(props.getProperty('STORE_FILE'))
                storePassword props.getProperty('STORE_PASSWORD')
                keyAlias props.getProperty('KEY_ALIAS')
                keyPassword props.getProperty('KEY_PASSWORD')
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
    }
}

// Fail at build time rather than at upload. EAS supplies its own credentials through injected
// properties; nothing is missing there.
tasks.matching { it.name ==~ /(assemble|bundle)Release/ }.configureEach {
    doFirst {
        def hasInjectedSigning = project.hasProperty('android.injected.signing.store.file')
        if (!releaseKeystoreProps.exists() && !hasInjectedSigning) {
            throw new GradleException(
                "No release signing configured: apps/mobile/keystore.properties is missing.\\n" +
                "Copy apps/mobile/keystore.properties.example to keystore.properties and fill it in.\\n" +
                "Without it this build would be signed with the debug keystore, which Play refuses."
            )
        }
    }
}
`

function withAndroidSigning(config) {
  return withAppBuildGradle(config, (mod) => {
    if (mod.modResults.contents.includes(MARKER)) return mod

    mod.modResults.contents += GRADLE_BLOCK
    return mod
  })
}

module.exports = withAndroidSigning
