const { withGradleProperties } = require('@expo/config-plugins')

// Off by default in the RN/Expo template. A release build spends most of its time in CMake tasks
// for third-party native libs (reanimated, worklets, mmkv, screens, gesture-handler) whose inputs
// never change between releases, so they are legitimate cache hits; the CI job caches ~/.gradle
// via gradle/actions/setup-gradle, so a hit survives across ephemeral runners.
//
// Set through a plugin because android/gradle.properties is regenerated by every prebuild.
function withGradleBuildCache(config) {
  return withGradleProperties(config, (mod) => {
    const caching = mod.modResults.find(
      (item) => item.type === 'property' && item.key === 'org.gradle.caching'
    )

    if (caching) {
      caching.value = 'true'
      return mod
    }

    // Comments are their own entries: folded into the property's `key` they would leave the guard
    // above unable to match, and a second pass would append a duplicate.
    mod.modResults.push(
      { type: 'empty' },
      {
        type: 'comment',
        value: 'Native library builds (reanimated, worklets, mmkv, screens, gesture-handler)',
      },
      {
        type: 'comment',
        value: 'have stable inputs release to release, so their compiled output is a legitimate',
      },
      { type: 'comment', value: 'cache hit across CI runs once ~/.gradle is restored.' },
      { type: 'property', key: 'org.gradle.caching', value: 'true' }
    )

    return mod
  })
}

module.exports = withGradleBuildCache
