const { withGradleProperties } = require('@expo/config-plugins')

// The Expo template ships `-Xmx2048m -XX:MaxMetaspaceSize=512m`. R8 runs inside the Gradle daemon
// and chews through Firebase, Play Services, RevenueCat and RN at once: past that budget it
// exhausts its metaspace and dies quietly, and `bundleRelease` then fails at
// :app:packageReleaseBundle on missing intermediates, which reads like a task-wiring bug and is
// not one. Grep the log for "out of JVM Metaspace".
//
// Set through a plugin because android/gradle.properties is regenerated by every prebuild. 4 GiB /
// 1 GiB stays sober because the same values run on a GitHub Actions runner with 16 GiB in total.
const JVM_ARGS = '-Xmx4096m -XX:MaxMetaspaceSize=1024m'

function withGradleMemory(config) {
  return withGradleProperties(config, (mod) => {
    const jvmArgs = mod.modResults.find(
      (item) => item.type === 'property' && item.key === 'org.gradle.jvmargs'
    )

    if (jvmArgs) {
      jvmArgs.value = JVM_ARGS
    } else {
      mod.modResults.push({ type: 'property', key: 'org.gradle.jvmargs', value: JVM_ARGS })
    }

    return mod
  })
}

module.exports = withGradleMemory
